### ISSUE TITLE
Create a Template for Making Guides/Templates

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/product-management#122]
### Action Items
- [x] Make a template issue
- [x] Add labels
   - [x] TG: Gather examples
   - [x] TG: Draft Template
   - [x] TG: Create Guide
   - [x] TG: Place Guide
```
### Action Items
- [  ] Gather examples of how other projects have done X
- [ ] Create a draft template, either in markdown or a google doc (in the product management google drive)
- [ ] Create a guide (usually google doc)
- [ ] Possibly create an issue template on .github 
   - [ ] _Add link to the template here_ (under resources)

### Resources

```
### Describe purpose or uses of Guide

**Comment by Olivia-Chiong** [comment]
### Overview
We need to create a guide to making [name of item] so that [purpose of the item]

### Action Items
- [ ] Gather examples of how other projects have done, adding each example as a link in the resources section
   - [ ] _Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label_
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)
    - [ ] _Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label_
- [ ] Create a guide on how to use the template 
   - [ ] _Once done, remove the "TG: Create Guide" label and add the "TG: Place Guide" label_
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
