### ISSUE TITLE
Guide to using Zoom at Hack for LA

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/product-management#172]
### Overview
We need to create Zoom meeting protocols to ensure all meetings are safe from bombing.

### Action Items
- [x] Remove all Zoom links from GitHub
- [x] Create guide for Zoom meeting settings and include the following information
   - [x] Meetings should be set up with password and/or waiting room
   - [x] Select Only registered zoom users allowed in meetings
   - [x] For meetings that are public facing, waiting room must be enabled and registration form used
   - [x] When a new member joins the team, make sure they are added to the calendar invite so that they can access the link there

### Resources/Instructions
[Zoom help file for authorised users](https://support.zoom.us/hc/en-us/articles/360037117472-authentication-profiles-for-meetings-and-webinars#:~:text=To%20enable%20only%20authenticated%20users%20can%20join%20meetings%20for%20your,can%20join%20meetings%20is%20enabled.)
[Guide to Using Zoom at Hack for LA](https://docs.google.com/document/d/1pidgtGeoA-yrjlWTz8Wts1h6DG5qpDRZeXULnBtgB4o/edit?usp=sharing)

![image](https://user-images.githubusercontent.com/75456721/110199075-61791f80-7e0b-11eb-9c0c-1fcf4be8fc45.png)

![image](https://user-images.githubusercontent.com/75456721/110199307-aea9c100-7e0c-11eb-81b0-f6e174369476.png)

**Comment by fchan218** [comment]
<details><summary>Prior version of issue</summary>
<p>

### Overview
We need to create Zoom meeting protocols to ensure all meetings are safe from bombing.

### Action Items
- [x] Remove all Zoom links from GitHub
- [x] Create guide for Zoom meeting settings and include the following information
   - [x] Meetings should be set up with password and/or waiting room
   - [x] Select Only registered zoom users allowed in meetings
   - [x] For meetings that are public facing, waiting room must be enabled and registration form used
   - [x] When a new member joins the team, make sure they are added to the calendar invite so that they can access the link there

### Resources/Instructions
[Zoom help file for authorised users](https://support.zoom.us/hc/en-us/articles/360037117472-authentication-profiles-for-meetings-and-webinars#:~:text=To%20enable%20only%20authenticated%20users%20can%20join%20meetings%20for%20your,can%20join%20meetings%20is%20enabled.)
[Guide to Using Zoom at Hack for LA](https://docs.google.com/document/d/1pidgtGeoA-yrjlWTz8Wts1h6DG5qpDRZeXULnBtgB4o/edit?usp=sharing)

![image](https://user-images.githubusercontent.com/75456721/110199075-61791f80-7e0b-11eb-9c0c-1fcf4be8fc45.png)

![image](https://user-images.githubusercontent.com/75456721/110199307-aea9c100-7e0c-11eb-81b0-f6e174369476.png)
</p>
</details>

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the Product Repo:</summary>
<p>
<img width="344" alt="Screenshot 2024-10-09 at 5 21 02 PM" src="https://github.com/user-attachments/assets/c895a5f1-4b5a-4ccc-aa70-da11a6a8131a">
</p>
</details>

**Comment by fchan218** [comment]
### Files in this Issue: 
[Guide to Using Zoom at Hack for LA](https://docs.google.com/document/d/1pidgtGeoA-yrjlWTz8Wts1h6DG5qpDRZeXULnBtgB4o/edit?usp=sharing)
- This file will need to be moved to the knowledgebase-content Google Drive

**Comment by fchan218** [comment]
@Olivia-Chiong This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).
