### ISSUE TITLE
Create a Guide: Product Analytics Best Practices

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/product-management#73]
### Overview
We need to create a guide to making Analytics so that we can get accurate metrics on users of your project

### Action Items
- [ ] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section
   - [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
- Refer to #123 for how to write a guide and the guide template
- Update issue #128 with the name of item you are working

#### Website Analytics
[Top 20 web analytics tools from survey of 2000+ experts](https://www.hotjar.com/web-analytics/tools/)

#### To see what analytics tool a project is using
Look up their domain name at https://builtwith.com

##### used on Hack for LA projects
- [Google Analytics](https://analytics.google.com/)
   - 311-data.org
- [Mixpanel](https://mixpanel.com/)
   - 311-data.org

#### Session Replay 
[List of Session Replay Software options](https://www.g2.com/categories/session-replay)

##### used on Hack for LA projects
- [HotJar](http://hotjar.com)
  - hackforla.org

**Comment by ExperimentsInHonesty** [comment]
@carolzjy are you still working on this guide, or do you want to be unassigned?

**Comment by carolzjy** [comment]
> @carolzjy are you still working on this guide, or do you want to be unassigned?
Hi Bonnie, I have not started working on this. I just un-assigned myself.

**Comment by ExperimentsInHonesty** [comment]
@carolzjy thanks!

**Comment by FeyiA** [comment]
#### Projects to check
- [100 Automations](https://github.com/100automations/website)
- [311 Data](https://github.com/hackforla/311-data)
- [Access the Data](https://github.com/hackforla/access-the-data)
- [BallotNav](https://github.com/hackforla/ballotnav)
- [Brigade Organizer's Playbook](https://github.com/codeforamerica/brigade-playbook)
- [Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend)
- [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs)
- [Civic Tech Structure](https://github.com/hackforla/civic-tech-structure)
- [Data Science Projects](https://github.com/hackforla/data-science)
- [Design Systems](https://github.com/hackforla/design-systems)
- [Engage](https://github.com/hackla-engage)
- [Expunge-Assist (formerly known as Record Clearance)](https://github.com/hackforla/expunge-assist)
- [Food Oasis](https://github.com/hackforla/food-oasis)
- [GreenEarthOS](https://github.com/hackforla/climate-project)
- [Guides](https://github.com/hackforla/guides) 
- [HomeUniteUs](https://github.com/hackforla/homeuniteus)
- [Internship project](https://github.com/hackforla/internship)
- [Lucky Parking](https://github.com/hackforla/lucky-parking)
- [Open Community Survey](https://github.com/hackforla/open-community-survey)
- [People Depot](https://github.com/hackforla/peopledepot)
- [TDM Calculator](https://github.com/hackforla/tdm-calculator)
- [VRMS](https://github.com/hackforla/vrms)
- [Hack for LA's Website](https://github.com/hackforla/website)
- [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/

**Comment by ExperimentsInHonesty** [comment]
@FeyiA It looks like you are making good progress.  
- I can help you with getting access to the documents on each of the teams.  Please remind me at the next meeting I see you at.
- For the Slack messages, please screen-shot them, they won't be there in April when our slack trial ends.

**Comment by FeyiA** [comment]
Work in progress. 

Changes made as advised.

Checking Slack channels first.

**Comment by ExperimentsInHonesty** [comment]
@FeyiA please make screen shots smaller and not in dark mode

**Comment by ExperimentsInHonesty** [comment]
@FeyiA it looks like you inserted an image for VRMS but it's not showing up properly.  See above.

**Comment by FeyiA** [comment]
Thank you for pointing this out. I have fixed it.

**Comment by ExperimentsInHonesty** [comment]
@FeyiA Please add the documents you are finding https://github.com/hackforla/guides/issues/94#issuecomment-1141250441 to this issue.

**Comment by FeyiA** [comment]
Will do, thank you.

**Comment by aymarmsba** [comment]
Outdated Description Content:

### Overview
We need to create a guide to making Analytics so that we can get accurate metrics on users of your project

### Action Items
- [x] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section
   - [x] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the ~[old product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)~ [new product management google drive>Product Management Guides](https://drive.google.com/drive/folders/1u9YOTWevHwEiHP8-r8d00rlqOn6q8e-5?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
- Refer to hackforla/product-management#123 for how to write a guide and the guide template
- Update issue hackforla/product-management#128 with the name of item you are working

#### Website Analytics
[Top 20 web analytics tools from survey of 2000+ experts](https://www.hotjar.com/web-analytics/tools/)

#### To see what analytics tool a project is using
Look up their domain name at https://builtwith.com

##### used on Hack for LA projects
- [Google Analytics](https://analytics.google.com/)
   - 311-data.org
- [Mixpanel](https://mixpanel.com/)
   - 311-data.org

#### Session Replay 
[List of Session Replay Software options](https://www.g2.com/categories/session-replay)

##### used on Hack for LA projects
- [HotJar](http://hotjar.com)
  - hackforla.org

**Comment by aymarmsba** [comment]
Assignee, Labels, Project Board Placement, and Milestones for this issue in the Product Repo:
![image](https://github.com/hackforla/product-management/assets/155505760/e875a723-363e-4644-8394-19acae3a9464)
